services:
  backend:
    build:
      context: ./backendSrc
    volumes:
    - uploads-data:/app/uploads
    env_file:
      - ./.env
    container_name: fastapi
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
      args:
        - REACT_APP_API_PROCESS_LOGIN=${REACT_APP_API_PROCESS_LOGIN}
        - REACT_APP_API_PROCESS_LOGIN_GG=${REACT_APP_API_PROCESS_LOGIN_GG}
        - REACT_APP_API_NOTES=${REACT_APP_API_NOTES}
        - REACT_APP_API_ADD_NOTE=${REACT_APP_API_ADD_NOTE}
        - REACT_APP_API_DELETE_NOTE=${REACT_APP_API_DELETE_NOTE}
        - REACT_APP_API_UPDATE_NOTE=${REACT_APP_API_UPDATE_NOTE}
        - REACT_APP_API_IMAGE_UPLOAD=${REACT_APP_API_IMAGE_UPLOAD}

    container_name: nginx-react
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
  uploads-data: